[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    '@openzeppelin/contracts=lib/openzeppelin-contracts/contracts',
    '@prb/math/=lib/prb-math/src/',
    '@solmate/=lib/solmate/src/',
    "@chainlink/contracts/src/v0.8/=lib/chainlink/contracts/src/v0.8",
]

[fuzz]
runs = 1000

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
