[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    '@prb/math/=lib/prb-math/src/',
    "@chainlink/contracts/src/v0.8/=lib/chainlink/contracts/src/v0.8",
    "@pyth/contracts/=lib/pyth-sdk-solidity/",
]

[fuzz]

solc_version = "0.8.23"
runs = 1000
# See more config options https://github.com/foundry-rs/foundry/tree/master/config
[invariant]
runs = 1000
fail_on_revert = true
